import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Input from "@/components/Input";
import Task from "@/components/Task";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export interface ITask {
  id: number;
  value: string;
  isCompleted: boolean;
}

export default function Home() {

  const [tasks, setTasks] = useState<ITask[]>([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-br from-primary to-secondary h-screen flex justify-center items-center">
        <div className="h-3/4 w-2/5 bg-tertiary rounded-2xl shadow-xl p-7 flex flex-col">
          <Input setTasks={setTasks} />
          <ul className="w-full grow overflow-y-auto">
            {tasks.map(task => {
              return <Task key={task.id} task={task} setTasks={setTasks} />
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
